Cypress.Commands.add ('Login', (username, password) => {
    cy.visit('https://automationteststore.com/index.php?rt=account/login')
    cy.get ('#loginFrm_loginname').type(username)
    cy.get ('#loginFrm_password').type(password)
    cy.get ('button[title="Login"]').click()
    cy.get ('#AccountFrm_firstname').type(firstName)
 cy.get ('#AccountFrm_lastname').type(lastName)
 cy.get ('button[title="Continue"]').click()
 cy.get ('#PasswordFrm_current_password').type(currentpassword)
 cy.get ('#PasswordFrm_password').type(newpassword)
 cy.get ('#PasswordFrm_confirm').type(newpasswordconfrirm)
 cy.get ('button[title="Continue"]').click()
})
