//Cypress.Commands.add ('Login', (username, password) => {
    //cy.visit('https://automationteststore.com/index.php?rt=account/login')
    //cy.get ('#loginFrm_loginname').type(username)
    //cy.get ('#loginFrm_password').type(password)
    //cy.get ('button[title="Login"]').click()
    //cy.get ('#AccountFrm_firstname').type(firstName)
 //cy.get ('#AccountFrm_lastname').type(lastName)
 //cy.get ('button[title="Continue"]').click()
 //cy.get ('#PasswordFrm_current_password').type(currentpassword)
 //cy.get ('#PasswordFrm_password').type(newpassword)
 //cy.get ('#PasswordFrm_confirm').type(newpasswordconfrirm)
 //cy.get ('button[title="Continue"]').click()
//})

Cypress.Commands.add ('RegisterUser', (user) => {
    cy.get ('[data-qa="signup-name"]').type(user.name)
    cy.get ('[data-qa="signup-email"]').type(user.email)
    cy.get ('button[data-qa="signup-button"]').click()
    cy.get ('#id_gender2').click()
        cy.get ('#name').type(user.name)
        cy.get ('#email').type(user.email)
        cy.get ('#password').type(user.password)
        cy.get ('#days').select(20)
        cy.get ('#months').select('january')
        cy.get ('#years').select(2000)
        cy.get ('#newsletter').click()
        cy.get ('#first_name').type(user.firstName)
        cy.get ('#last_name').type(user.lastName)
        cy.get ('#address1').type(user.addres)
        cy.get ('#country').select('canada')
        cy.get ('#state').type('canada')
        cy.get ('#city').type('tbilisi')
        cy.get ('#zipcode').type(1078)
        cy.get ('#mobile_number').type(597712848)
        cy.get ('button[data-qa="create-account"]').click()

})

Cypress.Commands.add ("loginuser", (email, password) => {
    cy.get ('[data-qa="login-email"]').type(email)
    cy.get ('[data-qa="login-password"]').type(password)
    cy.get ('button[data-qa="login-button"]').click()
})
